### ISSUE TITLE
unable to run - QtWebView v.1.15 not installed 

### ISSUE THREAD

**Issue by kieppie** [thevladsoft/Showerthoughts2#1]
(not a Qt dev)

Ubuntu 20.04 focal
Plasmoid2 v1.11

Getting an error QML file can't be loaded. 

Error loading QML file: file:///home/USERNAME/.local/share/plasma/plasmoids/showerthoughts2/contents/ui/main.qml:26:1: module "QtWebView" version 1.15 is not installed

Found similar issue @ https://stackoverflow.com/questions/42450333/qt-module-qtwebview-is-not-installed

installed: 

- libqt5webview5
- qml-module-qtwebview
- various QtWebEngine & QtWebKit  modules & libraries

`
libqt5webview5-dev/focal,now 5.12.8-0ubuntu1 amd64 [installed]
libqt5webview5/focal,now 5.12.8-0ubuntu1 amd64 [installed]
qml-module-qtwebview/focal,now 5.12.8-0ubuntu1 amd64 [installed]
`
Please advise

**Comment by thevladsoft** [comment]
Sorry for not answering before. I think the problem is with the version of libqt5webview5 on Ubuntu LTS. I uploaded a file called 

Showerthoughts2.qtwebview1.11.plasmoid 

Try with this one.
